name: Python CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install dependencies
      run: pip install pytest
    - name: run tests
      run: pytest
      working-directory: exercise-2
    # Add step to install dependencies

  lint:
    # Complete the lint job configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name : install dependencies
      run: pip install flake8
    - name: run flake8
      run: flake8 .
      working-directory: exercise-2

