name: my_own_action

on:
  push:
    branches:
      - master


jobs:
  lets-greet:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v4
    - id: foo
      uses: .github/actions/greeting/action.yml
      with: 
        names: "Kris"



  